collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.09661844
  brandStrength: 0.2787325
  lightness: 0.152444
  brandColors:
    - '#FFFFFF'
    - '#C72127'
    - '#0A2F88'
    - '#548EED'
    - '#E49396'
  rhythmicContrast: 0.6532382
typography_spectrum: 0.2658432
layout_spectrum: 0.5526316
name: Epmi01
